### ISSUE TITLE
[FEA]: Update examples to use optimized config for `nim_rag_eval_llm`

### ISSUE THREAD

**Issue by yczhang-nv** [NVIDIA/AIQToolkit#202]
### Is this a new feature, an improvement, or a change to existing functionality?

Improvement

### How would you describe the priority of this feature request

Low (would be nice)

### Please provide a clear description of problem this feature solves

Should update AIQ examples to use optimized config for `nim_rag_eval_llm`:
```yml
  nim_rag_eval_llm:
    _type: nim
    model_name: meta/llama-3.1-70b-instruct
    temperature: 0.0000001
    top_p: 0.0001
    max_tokens: 6
```
Ragas should work better with the config above.

### Describe your ideal solution

- Update the example configs as shown above
- Update the related docs

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
- [x] I have searched the [open feature requests](https://github.com/NVIDIA/AIQToolkit/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22%2Cimprovement%2Cenhancement) and have found no duplicates for this feature request
